"""add_sowing_date_to_users

Revision ID: 87da6e88fe45
Revises: 20260310_0001
Create Date: 2026-03-11 03:20:42.480784

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87da6e88fe45"
down_revision: str | None = "20260310_0001"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("sowing_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "sowing_date")
    # ### end Alembic commands ###
